name: willshex_storage_example
description: A command line tool example that uses willshex_storage

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.3
  meta: ^1.1.2
  willshex:
    path: ../willshex-dart
  willshex_storage:
    path: ../willshex-dart-storage

#dev_dependencies:
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
