name: dart_storage
description: A test command line application for testing dart storage

dependencies:
  http: ^0.11.3
  meta: ^1.1.2
  willshex:
    path: ../willshex-dart

#dev_dependencies:
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
