name: willshex_storage
description: A library for storing and querying data
version: 0.1.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^1.2.1
  fs_shim: ^2.3.0
  willshex:
    path: ../willshex-dart
  source_gen: ^4.0.0
  build: ^4.0.0
  analyzer: ^8.4.1

dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.4.10
